# Generated by Django 5.1.1 on 2024-10-03 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailingsettings",
            name="status",
            field=models.CharField(
                choices=[("completed", "Завершена"), ("created", "Создана")],
                default="created",
                max_length=20,
                verbose_name="Статус рассылки",
            ),
        ),
    ]
