# Generated by Django 5.1.1 on 2024-09-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0003_remove_message_settings_mailingsettings_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailingsettings",
            name="status",
            field=models.CharField(
                choices=[
                    ("completed", "Завершена"),
                    ("created", "Создана"),
                    ("launched", "Запущена"),
                ],
                default="created",
                max_length=20,
                verbose_name="Статус рассылки",
            ),
        ),
    ]
