# Generated by Django 5.1.1 on 2024-09-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0005_mailingsettings_next_sending"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailingsettings",
            name="end_on",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата и время окончания рассылки"
            ),
        ),
    ]
