# Generated by Django 4.2.2 on 2024-10-10 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blog_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="published_at",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата публикации"
            ),
        ),
    ]
